services:
  - type: web
    name: pokemon-blue
    runtime: docker
    plan: free
    repo: https://github.com/iSpyPuck/iSpyPuck
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
